arm:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: robot_arm_description_arm/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005000000000000001
  kinematics_solver_timeout: 0.10000000000000001
  kinematics_solver_attempts: 10
  position_only_ik: True
  
arm_2:
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_solver: robot_arm_description_arm/IKFastKinematicsPlugin
  kinematics_solver_search_resolution: 0.005000000000000001
  kinematics_solver_timeout: 0.10000000000000001
  kinematics_solver_attempts: 10
  position_only_ik: True
