controller_manager:
  ros__parameters:
    update_rate: 100  # ✅ Increased update rate for smoother execution

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController  # ✅ Kept as JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

gripper_controller:
  ros__parameters:
    joints:
      - joint_5
      # - joint_6  # ✅ Keep joint_6 if it mimics joint_5

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

joint_state_broadcaster:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
      - dummy_joint  # ✅ Only in joint_state_broadcaster, not in arm_controller
